#!/usr/bin/env ruby

require "plist"

snippets = []
Dir.foreach('snippets') do |item|
  next if item == '.' or item == '..'
  
  snippets << Plist::parse_xml(File.read("snippets/#{item}"))
end

snippets.sort! { |x, y| x["IDECodeSnippetTitle"] <=> y["IDECodeSnippetTitle"] }

result = ""

snippets.each do |snippet|
  result << "##### #{snippet["IDECodeSnippetTitle"]}\n"
  result << "Prefix: `#{snippet["IDECodeSnippetCompletionPrefix"]}`\n"
  result << """```objc
#{snippet["IDECodeSnippetContents"]}
```
"""
end

File.open("catalog.md", "w") do |f|
  f.write(result)
end
  