#!/usr/bin/env ruby

require "plist"

result = ""

Dir.foreach('snippets') do |item|
  next if item == '.' or item == '..'
  
  snippet = Plist::parse_xml(File.read("snippets/#{item}"))

  result << "##### #{snippet["IDECodeSnippetTitle"]}\n"
  result << "Prefix: `#{snippet["IDECodeSnippetCompletionPrefix"]}`\n"
  result << """```objc
#{snippet["IDECodeSnippetContents"]}
```
"""
end

File.open("catalog.md", "w") do |f|
  f.write(result)
end
  